### ISSUE TITLE
No informational version with latest .net core version

### ISSUE THREAD

**Issue by ChristophHornung** [MarkPflug/MSBuildGitHash#25]
MSBuildGitHash 2.0.1 doesn't seem to generate an informational version with .netcore3.1

Steps to reproduce:

- Create a new .netcoreapp3.1 project in VS2019
- Add MSBuildGitHash-2.0.1 nuget
- Build

(Used .net core 3.1.6)

=> The informational version is still 1.0.0. (the default) but the AssemblyMetadata GitHash is included correctly.

**Comment by ChristophHornung** [comment]
I found a workaround that seems to reliably fix the problem with 2.0.1. 

If we add this to the Directory.Build.targets (or the csproj) the informational version is correct afterwards.

    <Project>
	   <Target Name="FixGitHashOrder" DependsOnTargets="GetGitHash" BeforeTargets="AddSourceRevisionToInformationalVersion;"/>
    </Project>

**Comment by MarkPflug** [comment]
Thanks for bringing this to my attention. It looks like there were some changes to the Microsoft.NET.Sdk that affect this project. Three tests, which used to pass, are now failing. Hopefully, as you found, it's just a matter of adjusting where my targets run.

**Comment by MarkPflug** [comment]
I just pushed 2.0.2 to nuget which should fix this issue. You should be able to remove this custom target from your project now. Let me know if that doesn't fix this issue for you.

**Comment by ChristophHornung** [comment]
@MarkPflug The issue is fixed with the 2.0.2 version. Many thanks for the quick fix.

**Comment by KKire** [comment]
I still get default version to 1.0.0.0+hash. The project is on .NET Framework 4.8 running with MSBuildGitHash 2.0.2.

It results to `[assembly: AssemblyInformationalVersionAttribute("1.0.0.0+5545670")]` even though the AssemblyInfo.cs AssemblyVersion is different.
